Map<String, String> arabic = {
  'title1': "مرحبا بك في تطبيق ذاكر",
  "title2": "أنشئ اختبارك الخاص",
  "title3": "هل أنت مستعد؟",
  "body1":
      "هنا ستجد مجموعة متنوعة من الاختبارات المثيرة التي ستساعدك في قياس معرفتك و تقييم مهاراتك",
  "body2":
      "طريقة سهلة وفعالة لانشاء اختبارات شاملة تساعد الطلاب في تقييم معرفتهم ومهاراتهم",
  "body3":
      "مستعد لاختبار قدراتك و ارتقاء مستواك؟ انضم الينا الان وابدأ رحلة المعرفة والتحدي",
  "choosesubject": "اختر مادة",
  "topbar": "لنجعل هذا اليوم مليئ بالنجاح",
  "subject": "الوحدة",
  "lesson": "الدرس ",
  "youhavetoupgrade": "يتوجب عليك ترقية حسابك للوصول للوحدات المقفلة",
  "upgradenow": "الترقية الان",
  "sound": "الصوت والتأثيرات",
  "contactus": "اتصل بنا",
  "fontsize": "حجم الخط",
  "language": "اللغة",
  "logout": "تسجيل الخروج",
  "privacypolicy": "سياسة الخصوصية",
  "nointernet": "يوجد مشكلة في الاتصال, الرجاء المحاولة لاحقا",
  "resendcode": "اعادة ارسال الرمز",
  "pleasewait": "الرجاء الانتظار ",
  "minutes": " دقائق",
  "customerservices": "خدمة العملاء",
  "website": "الموقع الالكتروني",
  "whatsapp": "واتساب",
  "facebook": "فيس بوك",
  "instagram": "انستجرام",
  "gmail": "البريد الالكتروني",
  "empty": "لايمكن أن يكون فارغ",
  "more": "لايمكن أن يكون أكثر من ",
  "less": "لايمكن أن يكون أقل من ",
  "letters": " أحرف",
  "error": "خطأ",
  "myquizes": "اختباراتي",
  "createdby": "أنشأه ",
  "continue": "متابعة",
  "profile": "الملف الشخصي",
  "notifications": "الاشعارات",
  "savedquizes": "الاختبارات المحفوظة",
  "settings": "الإعدادات",
  "myinfo": "معلوماتي",
  "grade": "الصف",
  "city": "المدينة",
  "studentprofile": "الملف الشخصي",
  "me": "أنت",
  "exit": "الخروج من التطبيق",
  "seeall": "عرض الكل",
  "no": "لا",
  "yes": "نعم",
  "selectall": "تحديد الكل",
  "youhavecompleted": "لقد قمت بإكمال  ",
  "numoftests": " اختبارات في حسابك الحالي ",
  "hello": "مرحبا",
  "upgrade": "ترقية",
  "testsetings": "اعدادات الامتحان",
  "showcorrectanswer": "عرض الأجوبة الصحيحة فورا",
  "activatehelpmode": "تفعيل وضع المساعدة",
  "focusonexercises": "التركيز على التمارين التي أخطأت بها",
  "numofquestions": "عدد الأسئلة",
  "title": "عنوان الاختبار",
  "letusgo": "لننطلق",
  "keywords": "الكلمات المفتاحية",
  "editprofile": "تعديل الملف الشخصي",
  "firstname": "الاسم",
  "lastname": "اسم العائلة",
  "sex": "الجنس",
  "birthdate": "تاريخ الميلاد",
  "area": "المنطقة",
  "location": "العنوان",
  "savechanges": "حفظ التغييرات",
  "test": "اختبار",
  "question": "سؤال",
  "previous": "السابق",
  "next": "التالي",
  "done": "تم",
  "areyousure": "هل أنت متأكد؟",
  "exitexam": "الخروج من الامتحان",
  "hereareyourresults": "هذه هي نتائجك:",
  "wronganswer": "أجوبة خاطئة",
  "correctanswer": "أجوبة صحيحة",
  "duration": "المدة",
  "questions": "الأسئلة",
  "quizstate": "نتيجة الاختبار",
  "couldnotpass": "لم يتم الاجتياز",
  "redo": "إعادة الاختبار",
  "passed": "تم الاجتياز",
  "showmistakes": "عرض الاخطاء",
  "perfect": "أنت ممتاز",
  "congratulations": "مبروك لقد اجتزت الاختبار بنجاح",
  "failed": "أنت سيء",
  "save":"حفظ",
  "share":"مشاركة",
  "report":"إبلاغ",
  "notcongratulations": "للأسف الشديد لم يتم اجتياز الاختبار بنجاح",
  "allexams":"كل الاختبارات"
};
