Map<String, String> english = {
  "title1": "Welcome to our quiz app!",
  "title2": "Create your own test",
  "title3": "Are you ready?",
  "body1":
      "Here you will find a variety of exciting tests that will help you measure your knowledge and assess your skills.",
  "body2":
      " An easy and effective way to create comprehensive tests that help students assess their knowledge and skills",
  "body3":
      " Ready to test your abilities and level up? Join us now and start the journey of knowledge and challenge",
  "topbar": "Let's make this day a success",
  "subject": "Subject",
  "lesson": "Lesson ",
  "sound": "Sound",
  "contactus": "Contact us",
  "fontsize": "Font size",
  "language": "Language",
  "logout": "Logout",
  "privacypolicy": "Privacy policy",
  "nointernet": "Unfortunately there is a problem, try again later.",
  "minutes": " minutes",
  "resendcode": "Resend code",
  "pleasewait": "Please wait ",
  "customerservices": "Customer Services",
  "website": "Website",
  "whatsapp": "Whatsapp",
  "facebook": "Facebook",
  "instagram": "Instagram",
  "gmail": "Gmail",
  "empty": "Can't be empty",
  "more": "Can't be more than ",
  "less": "Can't be less than ",
  "letters": " letters",
  "error": "Error",
  "myquizes": "My Quizes",
  "createdby": "Created by ",
  "continue": "Continue",
  "profile": "Profile",
  "notifications": "Notifications",
  "savedquizes": "Saved Quizes",
  "settings": "Settings",
  "myinfo": "My information",
  "grade": "Grade",
  "city": "City",
  "studentprofile": "Profile",
  "warningbody": "Are you sure?",
  "warningtitle": "Exit app",
  "me": "Me",
  "seeall": "See all",
  "no": "No",
  "yes": "Yes",
  'selectall': "Select All",
  "hello": "Hello",
  "upgrade": "Upgrade",
  "youhavecompleted": "You have completed ",
  "numoftests": " out of 5 tests on your current account ",
  "testsetings": "Test Setings",
  "showcorrectanswer": "Show correct answer directly",
  "activatehelpmode": "Activate help mode",
  "focusonexercises": "Focus on exercises you missed",
  "numofquestions": "Num of questions",
  "title": "Title of quiz",
  "letusgo": "Let's go",
  "keywords": "Keywords",
  "editprofile": "Edit profile",
  "firstname": "First name",
  "lastname": "Last name",
  "sex": "Sex",
  "birthdate": "Birth date",
  "area": "Area",
  "location": "Location",
  "savechanges": "Save Changes",
  "test": "Test",
  "previous": "Previous",
  "next": "Next",
  "done": "Done",
  "areyousure": "Are you sure?",
  "exitexam": "Exit exam",
  "hereareyourresults": "Here are your results:",
  "wronganswer": "Wrong answer",
  "correctanswer": "Correct answer",
  "duration": "Duration",
  "questions": "Questions",
  "quizstate": "Quiz state",
  "couldntpass": "Could not pass",
  "redo": "Redo",
  "passed":"Passed",
  "showmistakes":"Show mistakes",
  "perfect":"!You are perfect",
  "congratulations":"Congratulations, you passed this test",
  "save":"Save",
  "share":"Share",
  "report":"Report",
};
